### ISSUE TITLE
could you please help me analysis my hiv dataset?

### ISSUE THREAD

**Issue by ghost** [blab/siv-cst#1]
@sidneymbell, I have a very good data set, could you please help me analysis it, my data set is also includes  many traits, thanks.

**Comment by sidneymbell** [comment]
I am unable to offer individual assistance, but you are more than welcome to adapt and reuse any of the code in this repository.

**Comment by ghost** [comment]
@sidneymbell, thanks for your kindly reply. Would you like to cooperate with me by using your analysis technology for  my data set to publish a paper, thanks. :)
